language: python
sudo: false

python:
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy3

before_install:
    - true

install:
    - pip install .

before_script:
    - true

script:
    - python -m unittest discover -s ./pyzenobase/tests -p '*.py'
