language: python
sudo: false

python:
    - 3.3
    - 3.4
    - 3.5
    - nightly

before_install:
    - pip install .

install:
    - true

before_script:
    - true

script:
    - python -m unittest discover -s ./pyzenobase/tests -p '*.py'
