#!/usr/bin/python3

import csv
import argparse
from datetime import datetime

import pyzenobase
    
BUCKET_NAME = "Battery - PyZenobase"
BUCKET_DESC = "Uploaded using PyZenobase (http://github.com/ErikBjare/PyZenobase)"

def upload_batterystats(filename, username, password, bucket_name=BUCKET_NAME, bucket_desc=BUCKET_DESC):
    """
        Works with CSVs generated by the Android app 'Battery Log' (https://play.google.com/store/apps/details?id=kr.hwangti.batterylog)
    """

    zapi = pyzenobase.ZenobaseAPI(username, password)
    bucket = zapi.create_or_get_bucket(bucket_name, description=bucket_desc)
    bucket_id = bucket["@id"]

    events = []
    with open(filename, newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        for row in reader:
            events.append({header[i]: row[i] for i in range(len(header))})

    print("Read {} events".format(len(events)))
    for event in events:
        # Transform data
        event["timestamp"] = pyzenobase.dt_to_timestamp(datetime.strptime(event.pop("datetime"), "%Y-%m-%d %H:%M:%S"), timezone="+01:00")
        event["tag"] = event.pop("status")
        event["percentage"] = float(event.pop("level"))
        event["temperature"] = {"@value": float(event.pop("temperature")), "unit": "C"}
        event.pop("voltage")

    print("Checking that events are valid...")
    events = [pyzenobase.ZenobaseEvent(event) for event in events]
    print("Uploading...")
    zapi.create_events(bucket_id, events)
    zapi.close()
    print("Done!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Upload batterystats')
    parser.add_argument("filename")
    parser.add_argument("username")
    parser.add_argument("password")

    args = parser.parse_args()

    upload_batterystats(args.filename, args.username, args.password)
